=== Azkona05/RetoFinalLMS/XSD/RetoFinalXSD.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="agenciaViajes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="aerolineas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="aerolinea" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="url" type="xs:string"/>
                                        <xs:element name="destinos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="destino" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre" type="xs:string"/>
                                                                <xs:element name="img">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="enlace" type="xs:string"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="descripcion" type="xs:string"/>
                                                            </xs:sequence>
                                                            <xs:attribute name="id" type="xs:integer"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="tipo">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="comercial"/>
                                                <xs:enumeration value="privada"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="usuarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="usuario" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="apellido" type="xs:string"/>
                                        <xs:element name="clave" type="xs:string"/>
                                        <xs:element name="numTel">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{9}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>                                        
                                        <xs:element name="contacto">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:choice minOccurs="1">
                                                        <xs:element name="correo" type="xs:string"/>
                                                        <xs:element name="numero2">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:integer">
                                                                    <xs:pattern value="\d{9}"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:element>
                                                    </xs:choice>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="sexo">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">                               
                                                <xs:enumeration value="M"/>
                                                <xs:enumeration value="F"/>
                                                <xs:enumeration value="O"/> 
                                            </xs:restriction>                                   
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="dni">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="\d{8}[A-Za-z]"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>         
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="vuelos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="vuelo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="destinoId" type="xs:integer"/>
                                        <xs:element name="fecha" type="xs:date"/>
                                        <xs:element name="pasajeros">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="pasajero" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="dni" type="xs:string"/>
                                                        </xs:complexType>                                                 
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="opiniones">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="opinion" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name = "estrellas" type = "xs:integer"/>
                                                                <xs:element name = "comentario" type = "xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:integer"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element> 
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Azkona05/RetoFinalLMS/XML/RetoFinalXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->
<agenciaViajes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="RetoFinalXSD.xsd">
    <aerolineas>
        <aerolinea tipo="comercial">
            <nombre>Ryanair</nombre>
            <url>https://www.ryanair.com/es/es</url>
            <destinos>
                <destino id = "1">
                    <nombre>Dublin</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Dublin"></img>
                    <descripcion>Capital de Irlanda, famosa por su historia y cultura.</descripcion>
                </destino>
                <destino id ="2">
                    <nombre>Londres</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Londres"></img>
                    <descripcion>Ciudad vibrante, conocida por sus museos y monumentos históricos.</descripcion>
                </destino>
            </destinos>
        </aerolinea>
        <aerolinea tipo="comercial">
            <nombre>Vueling</nombre>
            <url>https://www.vueling.com/</url>
            <destinos>
                <destino id = "3">
                    <nombre>Madrid</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Madrid"></img>
                    <descripcion>La capital de España, famosa por su vida nocturna y museos.</descripcion>
                </destino>
                <destino id = "4">
                    <nombre>Andorra</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Andorra"></img>
                    <descripcion>Un pequeño país montañoso entre Francia y España, ideal para deportes de invierno.</descripcion>
                </destino>
            </destinos>
        </aerolinea>
        <aerolinea tipo="comercial">
            <nombre>Volotea</nombre>
            <url>https://www.volotea.com/es/</url>
            <destinos>
                <destino id = "5">
                    <nombre>Roma</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Roma"></img>
                    <descripcion>La ciudad eterna, llena de historia y monumentos impresionantes.</descripcion>
                </destino>
                <destino id = "6">
                    <nombre>Atenas</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Atenas"></img>
                    <descripcion>Capital de Grecia, famosa por sus ruinas antiguas como la Acrópolis.</descripcion>
                </destino>
            </destinos>
        </aerolinea>
        <aerolinea tipo="comercial">
            <nombre>KLM</nombre>
            <url>https://www.klm.es</url>
            <destinos>
                <destino id = "7">
                    <nombre>Berlin</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\XML_XSD/Berlin"></img>
                    <descripcion>Capital de Alemania, famosa por su historia, museos y arquitectura moderna.</descripcion>
                </destino>
                <destino id = "8">
                    <nombre>Praga</nombre>
                    <img enlace=""></img>
                    <descripcion>Ciudad checa conocida por su castillo medieval y su casco antiguo.</descripcion>
                </destino>
            </destinos>
        </aerolinea>
        <aerolinea tipo="comercial">
            <nombre>Turkish Airlines</nombre>
            <url>https://www.turkishairlines.com/</url>
            <destinos>
                <destino id = "9">
                    <nombre>Turquia</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Turquia"></img>
                    <descripcion>Un país que une Europa y Asia, famoso por sus ruinas antiguas y paisajes únicos.</descripcion>
                </destino>
                <destino id = "6">
                    <nombre>Atenas</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Atenas"></img>
                    <descripcion>Capital de Grecia, famosa por sus ruinas antiguas como la Acrópolis.</descripcion>
                </destino>
            </destinos>
        </aerolinea>
        <aerolinea tipo="privada">
            <nombre>NetJets</nombre>
            <url>https://www.netjets.com/es-es/</url>
            <destinos>
                <destino id = "7">
                    <nombre>Berlin</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Berlin"></img>
                    <descripcion>Capital de Alemania, famosa por su historia, museos y arquitectura moderna.</descripcion>
                </destino>
                <destino id = "5">
                    <nombre>Roma</nombre>
                    <img enlace=""></img>
                    <descripcion>La ciudad eterna, llena de historia y monumentos impresionantes.</descripcion>
                </destino>
            </destinos>
        </aerolinea>
        <aerolinea tipo="privada">
            <nombre>Air Charter Service</nombre>
            <url>https://www.aircharterservice.es/</url>
            <destinos>
                <destino id = "2">
                    <nombre>Londres</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Londres"></img>
                    <descripcion>Ciudad vibrante, conocida por sus museos y monumentos históricos.</descripcion>
                </destino>
                <destino id = "3">
                    <nombre>Madrid</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Madrid"></img>
                    <descripcion>La capital de España, famosa por su vida nocturna y museos.</descripcion>
                </destino>
            </destinos>
        </aerolinea>
        <aerolinea tipo="privada">
            <nombre>Chapman</nombre>
            <url>https://chapmanfreeborn.aero/es/</url>
            <destinos>
                <destino id = "4">
                    <nombre>Andorra</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Andorra"></img>
                    <descripcion>Un pequeño país montañoso entre Francia y España, ideal para deportes de invierno.</descripcion>
                </destino>
                <destino id = "8">
                    <nombre>Praga</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Praga"></img>
                    <descripcion>Ciudad checa conocida por su castillo medieval y su casco antiguo.</descripcion>
                </destino>
            </destinos>
        </aerolinea>
        <aerolinea tipo="privada">
            <nombre>LunaJets</nombre>
            <url>https://www.lunajets.com/es</url>
            <destinos>
                <destino id = "9">
                    <nombre>Turquia</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Turquia"></img>
                    <descripcion>Un país que une Europa y Asia, famoso por sus ruinas antiguas y paisajes únicos.</descripcion>
                </destino>
                <destino id = "1">
                    <nombre>Dublin</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Dublin"></img>
                    <descripcion>Capital de Irlanda, famosa por su historia y cultura.</descripcion>
                </destino>
            </destinos>
        </aerolinea>
        <aerolinea tipo="privada">
            <nombre>Europair</nombre>
            <url>https://www.europair.com</url>
            <destinos>
                <destino id = "7">
                    <nombre>Berlin</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Berlin"></img>
                    <descripcion>Capital de Alemania, famosa por su historia, museos y arquitectura moderna.</descripcion>
                </destino>
                <destino id = "5">
                    <nombre>Roma</nombre>
                    <img enlace="C:\Users\anazk\OneDrive\Escritorio\RetoLMS\RECURSOS/XML_XSD/Roma"></img>
                    <descripcion>La ciudad eterna, llena de historia y monumentos impresionantes.</descripcion>
                </destino>
            </destinos>
        </aerolinea>
    </aerolineas>
    <usuarios>
        <usuario sexo="M" dni="12345678A">
            <nombre>Juan</nombre>
            <apellido>Pérez</apellido>
            <clave>clave123</clave>
            <numTel>654987321</numTel>
            <contacto>
                <correo>juanperez@example.com</correo>
            </contacto>         
        </usuario>
        <usuario sexo="F" dni="87654321B">
            <nombre>Maria</nombre>
            <apellido>González</apellido>
            <clave>clave456</clave>
            <numTel>612345678</numTel>
            <contacto>
                <numero2>555555555</numero2>
            </contacto>  
        </usuario>
    </usuarios>  
    <vuelos>
        <vuelo id="1">
            <destinoId>1</destinoId>
            <fecha>2025-04-10</fecha>
            <pasajeros>
                <pasajero dni="12345678A"/>
                <pasajero dni="87654321B"/>
            </pasajeros>
            <opiniones>
                <opinion>
                    <estrellas>5</estrellas>
                    <comentario>Excelente servicio, puntualidad y comodidad.</comentario>
                </opinion>
                <opinion>
